######################################################################
#
# File name : ArmLdmStmNextAddress_TB_wave.do
# Created on: Sun Jun 21 19:34:37 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
