######################################################################
#
# File name : ArmLdmStmNextAddress_TB_wave.do
# Created on: Wed Jun 24 14:05:47 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
