######################################################################
#
# File name : ArmLdmStmNextAddress_TB_elaborate.do
# Created on: Wed Jun 24 14:29:10 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vopt -64 +acc=npr -L xil_defaultlib -L simprims_ver -L secureip -work xil_defaultlib xil_defaultlib.ArmLdmStmNextAddress_TB xil_defaultlib.glbl -o ArmLdmStmNextAddress_TB_opt
