######################################################################
#
# File name : ArmRegisterBitAdder_TB.udo
# Created on: Wed Jun 24 14:54:08 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
