######################################################################
#
# File name : ArmRegisterBitAdder_TB_elaborate.do
# Created on: Wed Jun 24 15:37:23 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vopt -64 +acc=npr -L xil_defaultlib -L simprims_ver -L secureip -work xil_defaultlib xil_defaultlib.ArmRegisterBitAdder_TB xil_defaultlib.glbl -o ArmRegisterBitAdder_TB_opt
