######################################################################
#
# File name : ArmRegisterBitAdder_TB_simulate.do
# Created on: Wed Jun 24 15:37:24 CEST 2020
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -lib xil_defaultlib ArmRegisterBitAdder_TB_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ArmRegisterBitAdder_TB_wave.do}

view wave
view structure
view signals

do {ArmRegisterBitAdder_TB.udo}

run 1000ns
