#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Mentor Graphics Questa Advanced Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sun Jun 21 19:34:34 CEST 2020
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
bin_path="/afs/tu-berlin.de/units/Fak_IV/aes/tools/mentor/questasim/linux_x86_64"
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep source ArmLdmStmNextAddress_TB_compile.do 2>&1 | tee -a compile.log
