# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen.xci
# IP: The module: 'ArmClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen.xci
# IP: The module: 'ArmClkGen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /afs/tu-berlin.de/home/v/vincenthp2603/irb-ubuntu/HardwarePratikum/HardwarePRK-SoSe20/Blatt05/Vivado_WORK/Tutorial/vivado_project/HWP5/HWP5.srcs/sources_1/ip/ArmClkGen/ArmClkGen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ArmClkGen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
